<ips:template parameters="$group, $table" />
<div class="ipsPageHeader ipsClearfix ipsSpacer_bottom">
	<h1 class="ipsType_pageTitle">{$group->_title}</h1>
	{{if $group->description}}
		<div class='ipsPageHeader_info ipsType_normal'>
			{$group->description|raw}
		</div>
	{{endif}}
</div>
<div>
	{{if ( !$group AND \IPS\membermap\Markers\Groups::canOnAny( 'add' ) ) OR ( $group AND $group->can( 'add' ) ) }}
	<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_hidePhone ipsClearfix ipsSpacer_both">
		{template="groupButtons" group="markers" params="\IPS\membermap\Markers\Groups::canOnAny('add'), $group"}
	</ul>
	{{elseif $group AND $group->type == 'member' AND ! $group->can( 'add' ) AND $existing = \IPS\membermap\Map::i()->getMarkerByMember( \IPS\Member::loggedIn()->member_id, FALSE ) }}
		<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_hidePhone ipsClearfix ipsSpacer_both">
			<li class='ipsToolList_primaryAction'>{lang="membermap_only_one_marker" sprintf="$existing->url()"}</li>
		</ul>
	{{endif}}

	<div class='ipsBox'>
		{$table|raw}
	</div>

	{{if ( !$group AND \IPS\membermap\Markers\Groups::canOnAny( 'add' ) ) OR ( $group AND $group->can( 'add' ) ) }}
	<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_hidePhone ipsClearfix ipsSpacer_both">
		{template="groupButtons" group="markers" params="\IPS\membermap\Markers\Groups::canOnAny('add'), $group"}
	</ul>
	{{endif}}
</div>