<ips:template parameters="$group, $table" />
<div class="ipsPageHeader ipsClearfix ipsSpacer_bottom">
	<h1 class="ipsType_pageTitle">{$group->_title}</h1>
	{{if $group->description}}
		<div class='ipsPageHeader_info ipsType_normal'>
			{$group->description|raw}
		</div>
	{{endif}}
</div>
{{if \IPS\membermap\Markers\Groups::canOnAny('add') AND ( !$group OR $group->can('add') ) }}
<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_hidePhone ipsClearfix ipsSpacer_both">
	{template="groupButtons" group="markers" params="\IPS\membermap\Markers\Groups::canOnAny('add'), $group"}
</ul>
{{endif}}

<div class='ipsBox'>
{$table|raw}
</div>

{{if \IPS\membermap\Markers\Groups::canOnAny('add') AND ( !$group OR $group->can('add') ) }}
<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_hidePhone ipsClearfix ipsSpacer_both">
	{template="groupButtons" group="markers" params="\IPS\membermap\Markers\Groups::canOnAny('add'), $group"}
</ul>
{{endif}}