<ips:template parameters="$table, $headers, $markers" />
{{if count( $markers )}}
	{{foreach $markers as $marker}}
		{{$idField = $marker::$databaseColumnId;}}
		<li class='ipsDataItem {{if $marker->unread()}}ipsDataItem_unread{{endif}} {{if method_exists( $marker, 'tableClass' ) && $marker->tableClass()}}ipsDataItem_{$marker->tableClass()}{{endif}} {{if $marker->hidden()}}ipsModerated{{endif}}'>
			{{if member.member_id}}
				<div class='ipsDataItem_icon ipsPos_top'>
					{{if $marker->unread()}}
						<a href='{$marker->url( 'getNewComment' )}' title='{lang="first_unread_post"}' data-ipsTooltip>
							<span class='ipsItemStatus'><i class="fa {{if in_array( $marker->$idField, $table->contentPostedIn )}}fa-star{{else}}fa-circle{{endif}}"></i></span>
						</a>
					{{else}}
						{{if in_array( $marker->$idField, $table->contentPostedIn )}}
							<span class='ipsItemStatus ipsItemStatus_read ipsItemStatus_posted'><i class="fa fa-star"></i></span>
						{{else}}
							&nbsp;
						{{endif}}
					{{endif}}
				</div>
			{{endif}}
			<div class='ipsDataItem_main'>
				<h4 class='ipsDataItem_title ipsType_sectionHead'>
					<a href='{$marker->url()}' title='{lang="membermap_view_this_marker" sprintf="$marker->_title"}' {{if $marker->canEdit()}}data-role="editableTitle"{{endif}}>{wordbreak="$marker->_title"}</a>
					<br>
					<span class='ipsType_reset ipsType_normal ipsType_light ipsType_blendLinks'>
						{{if $marker->member_id > 0}}
							{lang="byline_nodate" htmlsprintf="$marker->author()->link()"}
						{{else}}
							{{$lang = \IPS\Member::loggedIn()->language()->addToStack( 'unknown' );}}
							{lang="byline_nodate" sprintf="$lang"}
						{{endif}}

						{{if \IPS\Request::i()->app != 'membermap'}}
							{lang="in"} <a href="{$marker->container()->url()}">{$marker->container()->_title}</a>
						{{endif}}
					</span>
				</h4>
				<p class='ipsDataItem_meta ipsType_reset ipsType_light ipsType_blendLinks'>
					<div class='ipsType_medium ipsType_richText ipsType_break ipsSpacer_top' data-ipstruncate='' data-ipstruncate-size='2 lines' data-ipstruncate-type='remove' style='word-wrap: break-word;'>
						{$marker->mapped( 'content' )|raw}
					</div>
				</p>
			</div>
			<div class='ipsDataItem_generic ipsDataItem_size9'>
				<ul class='ipsList_reset'>
					{{if $marker->location}}
						<li data-ipsTruncate data-ipsTruncate-size='1 lines' data-ipsTruncate-type='remove'>
							{{$location = trim( $marker->location, ',' );}}
							{$location}
						</li>
					{{endif}}
					<li>
						{{$dms = $marker->_latLngToDMS;}}
						<span data-ipsTooltip='' title="{$marker->lat}, {$marker->lon}">{$dms}</span>
					</li>
				</ul>
			</div>
			<ul class='ipsDataItem_lastPoster'>
				{{if $marker->container()->allow_comments}}
					<li>
						<span class='ipsDataItem_stats_number'>{number="$marker->mapped('num_comments')"}</span>
						<span class='ipsDataItem_stats_type'>{lang="comments" pluralize="$marker->mapped('num_comments')"}</span>
						{{if  \IPS\membermap\Markers\Markers::modPermission( 'unhide', NULL, $marker->container() ) AND $unapprovedComments = $marker->mapped('unapproved_comments')}}
							&nbsp;<a href='{$marker->url()->setQueryString( 'queued_comments', 1 )}' class='ipsType_warning ipsType_small ipsPos_right ipsResponsive_noFloat' data-ipsTooltip title='{lang="queued_posts_badge" pluralize="$marker->unapproved_comments"}'><i class='fa fa-warning'></i> <strong>{$unapprovedComments}</strong></a>
						{{endif}}
					</li>
				{{endif}}
				{{if $marker->container()->allow_reviews}}
					<li>
						<span class='ipsDataItem_stats_number'>{number="$marker->mapped('num_reviews')"}</span>
						<span class='ipsDataItem_stats_type'>
							{lang="reviews" pluralize="$marker->mapped('num_reviews')"}
							&nbsp;&nbsp;{template="rating" group="global" location="front" app="core" params="'large', $marker->averageReviewRating(), \IPS\Settings::i()->reviews_rating_out_of, $marker->memberReviewRating()"}
						</span>
					</li>
				{{endif}}
				<li>
					<p class='ipsType_normal ipsType_reset ipsType_light'>
						{{if $marker->updated > 0 OR $marker->added > 0}}
							{{if $marker->updated > $marker->added}}
								{lang="updated"} {datetime="$marker->updated"}
							{{else}}
								{lang="submitted"} {datetime="$marker->added"}
							{{endif}}
						{{endif}}
					</p>
				</li>
			</ul>
			
			{{if method_exists( $table, 'canModerate' ) AND $table->canModerate()}}
				<div class='ipsDataItem_modCheck'>
					<span class='ipsCustomInput'>
						<input type='checkbox' data-role='moderation' name="moderate[{$marker->id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $marker ) )"}" data-state='{{if $marker->tableStates()}}{$marker->tableStates()}{{endif}}'>
						<span></span>
					</span>
				</div>
			{{endif}}
		</li>
	{{endforeach}}
{{endif}}