<ips:template parameters="$event, $today" />
<div class='ipsDataItem_icon cCalendar_date_overlay'>
	{{if $event->nextOccurrence( $today, 'startDate' )}}
		<time datetime='{$event->nextOccurrence( $today, 'startDate' )->mysqlDatetime()}' class='ipsCalendarDate'>
			<span class='ipsCalendarDate_month'>{$event->nextOccurrence( $today, 'startDate' )->monthNameShort}</span>
			<span class='ipsCalendarDate_date'>{$event->nextOccurrence( $today, 'startDate' )->mday}</span>
		</time>
	{{else}}
		<time datetime='{$event->lastOccurrence( 'startDate' )->mysqlDatetime()}' class='ipsCalendarDate'>
			<span class='ipsCalendarDate_month'>{$event->lastOccurrence( 'startDate' )->monthNameShort}</span>
			<span class='ipsCalendarDate_date'>{$event->lastOccurrence( 'startDate' )->mday}</span>
		</time>
	{{endif}}
</div>
<div class='ipsDataItem_main cWidgetComments'>
	<div class='ipsType_break ipsContained'>
		<a href="{$event->url()}" title='{lang="view_this_event" sprintf="$event->title"}'  target='_blank' rel="nooptimize">{$event->title}</a>
	</div>
	<strong class='ipsType_small'>
		{{if $event->nextOccurrence( $today, 'startDate' )}}
			{$event->nextOccurrence( $today, 'startDate' )->calendarDate()}{{if !$event->all_day}} {$event->nextOccurrence( $today, 'startDate' )->localeTime( FALSE )} {{endif}}
			{{if $event->nextOccurrence( $event->nextOccurrence( $today, 'startDate' ) ?: $today, 'endDate' ) }}
				{{if $orientation == 'vertical'}}<br>{{endif}}
				<span class='ipsType_light ipsType_unbold'>{lang="until"}</span>{{if $orientation == 'vertical'}}<br>{{endif}}
				{$event->nextOccurrence( $event->nextOccurrence( $today, 'startDate' ) ?: $today, 'endDate' )->calendarDate()}{{if !$event->all_day}} {$event->nextOccurrence( $event->nextOccurrence( $today, 'startDate' ) ?: $today, 'endDate' )->localeTime( FALSE )}{{endif}}
			{{endif}}
		{{else}}
			{$event->lastOccurrence( 'startDate' )->calendarDate()}{{if !$event->all_day}} {$event->lastOccurrence( 'startDate' )->localeTime( FALSE )} {{endif}}
			{{if $event->lastOccurrence( 'endDate' ) }}
				{{if $orientation == 'vertical'}}<br>{{endif}}
				<span class='ipsType_light ipsType_unbold'>{lang="until"}</span>{{if $orientation == 'vertical'}}<br>{{endif}}
				{$event->lastOccurrence( 'endDate' )->calendarDate()}{{if !$event->all_day}} {$event->lastOccurrence( 'endDate' )->localeTime( FALSE )}{{endif}}
			{{endif}}
		{{endif}}
	</strong>
	<br>
	<div class='membermap_popupContent'>
		{$event->truncated()|raw}
	</div>
</div>