<ips:template parameters="$marker" />
<p class='ipsType_large'>
	<a href='{$marker->url()}' target='_blank' rel="nooptimize">
		{$marker->name}
	</a>
</p>
{{if $marker->container()->allow_reviews AND $marker->mapped( 'num_reviews' ) > 0 }}
	{template="rating" group="global" location="front" app="core" params="'large', $marker->averageReviewRating(), \IPS\Settings::i()->reviews_rating_out_of, $marker->memberReviewRating()"}
{{endif}}

<div class='membermap_popupContent'>{$marker->description|raw}</div>

{{if $marker->location}}
	<p>{$marker->location}</p>
{{endif}}

{{if $marker->container()->allow_comments OR $marker->container()->allow_reviews}}
	<ul class="ipsList_inline">
		{{if $marker->container()->allow_comments }}
			<li class='ipsType_light ipsType_small'>
				<a href="{$marker->lastCommentPageUrl()}" target='_blank' rel="nooptimize">
					<i class='fa fa-comment'></i> {lang="marker_comment_count" pluralize="$marker->mapped('num_comments')"}
				</a>
			</li>
		{{endif}}
		{{if $marker->container()->allow_reviews}}
			<li class='ipsType_light ipsType_small'>
				<a href="{$marker->lastReviewPageUrl()}" target='_blank' rel="nooptimize">
					{lang="marker_review_count" pluralize="$marker->mapped('num_reviews')"} 
				</a>
			</li>
		{{endif}}
	</ul>
{{endif}}