<ips:template parameters="$marker" />
<h3>
	<a href='{url="app=membermap&module=markers&controller=markers&id={$marker['marker_id']}" seoTemplate="markers_marker" seoTitle="$marker['marker_name_seo']"}' target='_blank' rel="nooptimize">
		{$marker['marker_name']}
	</a>
</h3>
<div class='membermap_popupContent'>{$marker['marker_description']|raw}</div>
{{if $marker['marker_location']}}
	<p>{$marker['marker_location']}</p>
{{endif}}