<ips:template parameters="$marker, $photo" />
<h3>
	<img src='{$photo}' itemprop='image' alt='' class='ipsUserPhoto ipsUserPhoto_mini'> 
	<a href='{url="app=core&module=members&controller=profile&id={$marker['member_id']}" seoTemplate="profile" seoTitle="$marker['members_seo_name']"}' target='_blank'>{$marker['marker_name']}</a>
</h3>
{{if $marker['marker_location']}}
	<p>{$marker['marker_location']}</p>
{{endif}}