<ips:template parameters="$markers=''" />
<div class="ipsPageHeader ipsClearfix">
	<header class='ipsSpacer_bottom'>
		<h1 class="ipsType_pageTitle">{lang="frontnavigation_membermap"}</h1>
		<div class='ipsPos_right ipsResponsive_noFloat ipsResponsive_hidePhone'>
			<ul class="ipsToolList ipsToolList_horizontal ipsClearfix">
				<li class='ipsToolList_primaryAction'>
					<a class="ipsButton ipsButton_medium ipsButton_important ipsButton_fullWidth" href="#" title='' id="membermap_button_addLocation">{lang="membermap_button_addLocation"}</a>
				</li>
			</ul>
		</div>
	</header>
</div>

<section>
	<div id='membermapWrapper'>
		<div id="mapWrapper" class='ipsLayout_content clearfix'>
			<div id='mapCanvas'></div>
		</div>
	</div>
</section>

<div id='mapMarkers' class='ipsHide'>{$markers|raw}</div>