<?php

$lang = array(
	'__app_membermap'	=> "Member Map",
	'frontnavigation_membermap'	=> "Member Map",
	'menu__membermap_membermap' => "Member Map",
	'module__membermap_membermap' => "Member Map",
	'group__membermap_membermap' => "Member Map",
	'loc_membermap_viewing_membermap' => "Viewing the Member Map",
	'g_membermap_canAdd' => "Can add location to map",
	'g_membermap_canEdit' => "Can edit their location",
	'g_membermap_canDelete' => "Can delete their location",
	'g_membermap_markerColour' => "Marker Colour",
	'g_membermap_markerColour_desc' => "The members own marker will always be green",
	'menu__membermap_membermap_markers' => 'Custom Markers',
	'menu__membermap_membermap_mapmanager' => "Map Manager",
	'membermap_mapmanager_activeMaps' => "Active Maps",
	'membermap_mapmanager_availMaps' => "Available Maps",
	'membermap_mapmanager_activeOverlays' => "Active Overlays",
	'membermap_mapmanager_availOverlays' => "Available Overlays",
	'membermap_button_addLocation' => "Add Location",
	'membermap_button_editLocation' => "Update Location",
	'membermap_current_location' => "Use Current Location",
	'membermap_geolocation_desc' => "This will use a feature in your browser to detect your current location using GPS, Cellphone triangulation, Wifi, Router, or IP address",
	'membermap_add_marker' => "Add Custom Marker",
	'membermap_add_group' => "Add Custom Marker Group",
	'membermap_edit_marker' => "Edit Custom Marker",
	'membermap_form_location' => "Search for your location",
	'membermap_form_placeholder' => "Enter your address / city / county / country, you can be as specific as you like",
	'membermap_button_myLocation' => "My Location",

	'membermap_error_cantEdit' => "You are not allowed to edit your location.",
	'membermap_error_cantAdd' => "You are not allowed to add a location.",
	'membermap_error_noGroups' => "You need to create a Custom Marker Group first.",
	'membermap_showing_markers'	=> "Showing <span>0</span> markers",

	'membermap_view_fullsize' => "View fullsize map",

	'group_contrast_warning' => "Your users may have trouble seeing the icon on the background, the contrast of the colours is too close.",
	'group_marker_example' => "Marker Preview",
	'group_name' => "Marker Group Name",
	'group_pin_icon' => "Marker Icon",
	'group_pin_icon_desc' => "Choose any icon from the <a href='http://fontawesome.io/icons/' target='_blank'>Font Awesome 4.2 icon set</a>, input the full name in the box above, i.e. `fa-map-marker`",
	'group_pin_colour' => "Marker Icon Colour",
	'group_pin_bg_colour' => "Marker Background Colour",

	'marker_name' => "Marker Title",
	'marker_description' => "Marker Description",
	'marker_lat' => "Latitude (N)",
	'marker_location' => "Location",
	'marker_location_desc' => "Enter a location above to search for one, enter the latitude and longitude manually below, or select the location in a map",
	'marker_lon' => "Longitude (E)",
	'marker_parent_id' => "Marker Group",
	'marker_addViaMap' => "Show in map",
	'marker_addViaMap_button' => "Select location in map",
	'membermap_goHome' => "Go to my location",
	'membermap_rebuildBrowserCache' => "Rebuild Browser Cache",
	'membermap_rebuildServerCache' => "Rebuild Server Cache (Last Update: %s)",
);
