<?php

$lang = array(

	/* Various strings */
	'__app_membermap'							=> "Member Map",
	'frontnavigation_membermap'					=> "Member Map",
	'membermap_clubnavtitle'					=> "Member Map",
	'__indefart_membermap_marker'				=> "a Member Map marker",
	'__indefart_membermap_markers_comment'		=> "a comment on a Member Map marker",
	'__indefart_membermap_markers_review'		=> "a review on a Member Map event",
	'__defart_membermap_marker'					=> "Member Map marker",
	'__defart_membermap_markers_comment'		=> "comment on a Member Map marker",
	'__defart_membermap_markers_review'			=> "review on a Member Map marker",
	'filestorage__membermap_MarkerStaticMap' 	=> "Member Map Embed Preview Image",

	'membermap_rebuilding_cache'				=> "Rebuilding Member Map Cache",

	'membermap_group_sg'						=> "feature (NOT WORKING)",

	/* ACP Module/Menu titles */
	'menu__membermap_membermap'					=> "Member Map",
	'menu__membermap_membermap_markers' 		=> 'Marker Groups',
	'menu__membermap_membermap_mapmanager'	 	=> "Map Manager",
	'menu__membermap_membermap_settings' 		=> "Settings",

	'module__membermap_membermap' 				=> "Member Map",
	'module__membermap_markers' 				=> "Marker Groups",
	'group__membermap_membermap' 				=> "Member Map",

	'membermap_group'							=> "Marker Groups",


	/* ACP Restrictions */
	'r__mapmanager' 			=> "Map Manager",
	'r__mapmanager_manage' 		=> "Can manage Map Manager?",
	'r__markers' 				=> "Marker Groups",
	'r__markers_manage' 		=> "Can view Custom Markers?",
	'r__markers_add' 			=> "Can add Custom Markers?",
	'r__markers_edit' 			=> "Can edit Custom Markers?",
	'r__markers_delete' 		=> "Can delete Custom Markers?",
	'r__markers_permissions' 	=> "Can manage permissions?",

	'membermap_marker_groups' 	=> "Marker Groups",
	'membermap_groups' 			=> "Groups",

	/* ACP Mod Permissions */
	'modperms__core_Content_membermap_Markers_Markers' => "Member Map",
	'membermap_markers_groups'						=> "Marker Groups",
	'can_edit_membermap_marker'						=> "Can edit markers?",
	'can_hide_membermap_marker'						=> "Can hide markers?",
	'can_unhide_membermap_marker'					=> "Can unhide markers?",
	'can_view_hidden_membermap_marker'				=> "Can view hidden markers?",
	'can_move_membermap_marker'						=> "Can move markers?",
	'can_delete_membermap_marker'					=> "Can delete markers?",
	'can_feature_membermap_marker'					=> "Can feature markers?",
	'can_unfeature_membermap_marker'				=> "Can unfeature markers?",
	'can_edit_membermap_marker_comment'				=> "Can edit comments?",
	'can_hide_membermap_marker_comment'				=> "Can hide comments?",
	'can_unhide_membermap_marker_comment'			=> "Can unhide comments?",
	'can_view_hidden_membermap_marker_comment'		=> "Can view hidden comments?",
	'can_delete_membermap_marker_comment'			=> "Can delete comments?",
	'can_edit_membermap_marker_review'				=> "Can edit reviews?",
	'can_hide_membermap_marker_review'				=> "Can hide reviews?",
	'can_unhide_membermap_marker_review'			=> "Can unhide reviews?",
	'can_view_hidden_membermap_marker_review'		=> "Can view hidden reviews?",
	'can_delete_membermap_marker_review'			=> "Can delete reviews?",
	'can_feature_comments_membermap_marker'			=> "Can recommend comments on markers?",
	'can_unfeature_comments_membermap_marker'		=> "Can remove comments recommendations on markers?",
	'can_add_item_message_membermap_marker'			=> "Can add messages to markers?",
	'can_edit_item_message_membermap_marker'		=> "Can edit messages on markers?",
	'can_delete_item_message_membermap_marker'		=> "Can delete messages on markers?",

	/* Front-end marker view */
	'membermap_marker_info' 		=> "Marker Information",
	'membermap_marker_author' 		=> "Added by",
	'membermap_marker_date' 		=> "Submitted",
	'membermap_marker_updated' 		=> "Updated",
	'membermap_marker_location' 	=> "Location",
	'membermap_marker_coordinates' 	=> "Coordinates",
	'group_markers_number' 			=> "{# [1:marker][?:markers]}",
	'group_markers_number_noCount' 	=> "{!# [1:marker][?:markers]}",
	'marker_actions' 				=> "Marker Actions",
	'report_marker' 				=> "Report this marker",
	'membermap_marker' 				=> "Member Map Marker",
	'membermap_marker_pl'			=> "Markers",
	'membermap_marker_pl_lc'		=> "markers",
	'membermap_markers_markers_pl' 	=> "Member Map",
	'membermap_markers_comment'			=> "Marker Comment",
	'membermap_markers_comment_pl'		=> "Marker Comments",
	'membermap_markers_comment_pl_lc'	=> "marker comments",
	'membermap_markers_review'			=> "Marker Review",
	'membermap_markers_review_pl'		=> "Marker Reviews",
	'membermap_markers_review_pl_lc'	=> "marker reviews",
	'marker_comment_count'			=> "{# [1:Comment][?:Comments]}",
	'marker_review_count'			=> "{# [1:Review][?:Reviews]}",
	'reviews'						=> "{!#[1:review][?:reviews]}",
	'marker_submit_comment'			=> "Submit Comment",
	'membermap_view_this_marker' 	=> "View this marker: %s",
	'membermap_submit_a_marker' 	=> "Add Marker",
	'membermap_edit_a_marker' 		=> "Edit Marker",
	'membermap_no_markers_in_cat'	=> "There are no markers in this group",
	'membermap_submit_first_marker' => "Why don't you submit the first one?",
	'membermap_pending_approval'	=> "This marker is not yet approved and is currently only visible to staff.",
	'membermap_delete_title'		=> "Delete this marker",
	'membermap_approve_title'		=> "Approve this marker",
	'marker_type'					=> "Filter",
	'queued_markers'				=> "Unapproved markers",
	'marker_time_frame'				=> "Last Update",
	'all_markers'					=> "All",
	'marker_rating_value'			=> "Your Rating",
	'marker_review_text'			=> "Your Review",
	'marker__review_placeholder'	=> "Add a review...",
	'marker__comment_placeholder'	=> "Add a comment...",
	'feature_title_marker'			=> "Feature this marker",
	'unfeature_title_marker'		=> "Unfeature this marker",

	'no_marker_review'				=> "You do not have permission to review markers",


	/* Session Location */
	'loc_membermap_viewing_membermap' 	=> "Viewing Member Map",
	'loc_membermap_viewing_group'		=> "Viewing Member Map marker group: %s",
	'loc_membermap_browsing_groups'		=> "Viewing Member Map marker groups",
	'loc_membermap_viewing_marker'		=> "Viewing Member Map marker: %s",


	/* ACP Settings */	
	'map_settings' 						=> "Map Settings",
	'api_settings' 						=> "API Keys",
	'membermap_settings_tab_general' 	=> 'General',
	'membermap_settings_tab_profile' 	=> 'Profile sync',
	'membermap_settings_tab_calendar' 	=> 'Calendar ext.',
	'membermap_settings_tab_clubs' 		=> 'Clubs ext.',
	'membermap_settings_tab_pages' 		=> 'Pages ext.',
	'membermap_enable_clustering' 		=> "Enable Marker Clustering?",
	'membermap_bbox_location' 			=> "Define Forced Bounding Box",
	'membermap_bbox_location_desc' 		=> "Use the field above to search for a location that will always be in center of your map. The map will only focus on this area, regardless of markers outside of it. Try a few of the results from the search untill you find one that suits your needs.",
	'membermap_mapQuestAPI' 			=> "MapQuest API Key",
	'membermap_mapQuestAPI_desc' 		=> "Sign up for your own personal API Key at <a href='https://developer.mapquest.com/' target='_blank'>MapQuest</a>. This is required for the map to work.",
	'membermap_bbox_zoom' 				=> "Default Zoom Level",
	'membermap_bbox_zoom_desc' 			=> "Only affective when a bounding box is defined.",
	'membermap_showNightAndDay'			=> "Show a 'night and day' overlay",
	'membermap_showMemberList'			=> "Show a list of markers in the sidebar?",
	'membermap_groupByMemberGroup'		=> "Group member markers by member group?",
	'membermap_highlightStaff'			=> "Group members of staff on top of sidebar?",
	'membermap_autoUpdate'				=> "Profile location synchronisation",
	'membermap_monitorLocationField' 	=> "Enable profile sync?",
	'membermap_profileLocationField' 	=> "Select profile field(s)",
	'membermap_profileLocationField_desc' => "Select the custom profile field(s) where members enter their location. You can add multiple fields here, and the first populated profile field will be selected.<br>If you change this setting, and the setting below to import members is enabled, you may have to <a href='{internal.app=membermap&module=membermap&controller=settings&do=resetMemberSync}'>restart the sync process</a> for this to have any effect. <strong>This will not affect existing markers on the map.</strong>",
	'membermap_monitorLocationField_groupPerm' => "Enable for",
	'membermap_syncLocationField'		=> "Import members without a map marker?",
	'membermap_syncLocationField_desc'	=> "This will import members that have a location set in the profile, but not one in the map. This will turn itself off once all members are processed.<br><a href='{internal.app=membermap&module=membermap&controller=settings&do=resetMemberSync}'>Restart sync process</a>",
	'membermap_calendarExt_header'		=> "Calendar Extension",
	'membermap_calendarExt'				=> "Enable Calendar Extension?",
	'membermap_calendarExt_desc'		=> "When enabled, this will show upcoming events that have specified a location.",
	'membermap_calendars'				=> "Enabled calendars",
	'membermap_calendar_days_ahead'		=> "Number of days ahead to show",
	'membermap_calendar_icon'			=> "Marker Icon",
	'membermap_calendar_icon_desc'		=> "Choose any icon from the <a href='https://fontawesome.com/v4.7.0/icons/' target='_blank'>Font Awesome icon set</a>, input the full name in the box above, i.e. `fa-calendar`",
	'membermap_calendar_colour'			=> "Marker Icon Colour",
	'membermap_calendar_bgcolour'		=> "Marker Pin Colour",
	'membermap_calendar_marker_example'	=> "Marker Preview",
	'membermap_clubsExt_header'			=> "Clubs Extension",
	'membermap_clubsExt'				=> "Enable Clubs Extension?",
	'membermap_clubs'					=> "Enabled Clubs",
	'membermap_clubs_icon'				=> "Marker Icon",
	'membermap_clubs_icon_desc'			=> "Choose any icon from the <a href='https://fontawesome.com/v4.7.0/icons/' target='_blank'>Font Awesome icon set</a>, input the full name in the box above, i.e. `fa-users`",
	'membermap_clubs_colour'			=> "Marker Icon Colour",
	'membermap_clubs_bgcolour'			=> "Marker Pin Colour",
	'membermap_clubs_marker_example'	=> "Marker Preview",
	'membermap_clubs_showClubLocations' => "If a club have a physical location, show this on the map?",
	'membermap_clubs_showClubLocations_desc'	=> "<a href='{internal.app=core&module=applications&controller=enhancements&do=edit&id=core_GoogleMaps}' target='_blank'>Google Maps integration</a> and <a href='{internal.app=core&module=clubs&controller=settings&searchResult=clubs_locations}' target='_blank'>'Clubs have physical locations?'</a> needs to be enabled for this to work.",
	'membermap_clubs_showInClubHeader' 	=> "Show a link to \"Member Map\" in the clubs header",
	'membermap_clubs_showInClubHeader_desc' => "This will open a map that shows the location of the club members that also have a Member Map marker",
	'membermap_pagesExt_header'			=> "Pages Extension",
	'membermap_pagesExt'				=> "Enable Pages Extension?",
	'membermap_pagesExt_desc'			=> "When enabled, this will show database records that have specified a location.",
	'membermap_pages_databases'			=> "Enabled databases",
	'membermap_pages_databases_desc'	=> "Note: This will only show databases that have a field of the type 'Address'.",
	'membermap_pages_days_behind'		=> "From the last X days",
	'membermap_pages_icon'				=> "Marker Icon",
	'membermap_pages_icon_desc'			=> "Choose any icon from the <a href='https://fontawesome.com/v4.7.0/icons/' target='_blank'>Font Awesome icon set</a>, input the full name in the box above, i.e. `fa-pages`",
	'membermap_pages_colour'			=> "Marker Icon Colour",
	'membermap_pages_bgcolour'			=> "Marker Pin Colour",
	'membermap_pages_marker_example'	=> "Marker Preview",
	'membermap_resetmembersync'			=> "Restart sync process",
	'membermap_resetmembersync_desc'	=> "Re-process all your members who don't already have a Member Map marker?",
	'membermap_restrictCountries'		=> "Limits the location search to specific countries",
	'membermap_restrictCountries_desc'	=> "This allows you to only get results from the selected countries when searching for a location. Works in both the \"Add Location\" form and profile synchronisation.",
	'membermap_noRestriction'			=> "--- NO RESTRICTION ---",
	'membermap_privacy'					=> "Privacy",
	'membermap_hideMarkerContent'		=> "Hide location for member markers",
	'membermap_hideMarkerContent_desc'	=> "Some markers reveal the exact address for some members. Enable this to hide this information from all member markers. Markers in other groups are not affected",
	'membermap_showProfileMap'			=> "Show minimap in the member's profile?",
	'membermap_popupSettings'			=> "Map popup settings",
	'membermap_popupFields'				=> "Additional profile fields to show",

	/* ACP Marker Group Settings */
	'g_membermap_markerColour' 		=> "Marker Colour",
	'g_membermap_markerColour_desc' => "The members own marker will always be green",
	'g_membermap_delete_own'		=> "Can delete own markers?",
	'group_marker_example' 			=> "Marker Preview",
	'group_name' 					=> "Marker Group Name",
	'group_pin_icon' 				=> "Marker Icon",
	'group_pin_icon_desc' 			=> "Choose any icon from the <a href='https://fontawesome.com/v4.7.0/icons/' target='_blank'>Font Awesome icon set</a>, input the full name in the box above, i.e. `fa-map-marker`",
	'group_pin_colour' 				=> "Marker Icon Colour",
	'group_pin_bg_colour' 			=> "Marker Background Colour",
	'group_pin_bg_colour_white' 	=> "White",
	'group_moderate' 				=> "Markers must be approved?",
	'membermap_import'				=> "Import Markers",
	'membermap_add_group' 			=> "Add Custom Marker Group",
	'import_upload'					=> "Marker .kml file",
	'import_creategroups'			=> "Create a new group",
	'import_creategroups_desc'		=> "Import markers to an existing group, or create a new group for each \"Folder\" in the .kml file",
	'membermap_error_no_id_no_create'	=> "You have to either chose to create a new group, or select an existing group to import markers to",
	'membermap_import_thumbup'			=> "Successfully imported %d markers",
	'group_comment_moderate'			=> "Comments must be approved?",
	'group_allow_comments'				=> "Allow comments?",
	'group_allow_reviews'					=> "Allow reviews?",
	'group_review_moderate'				=> "Reviews must be approved?",


	/* ACP Map Manager */
	'membermap_mapmanager_activeMaps' 		=> "Active Maps",
	'membermap_mapmanager_availMaps' 		=> "Available Maps",
	'membermap_mapmanager_activeOverlays' 	=> "Active Overlays",
	'membermap_mapmanager_availOverlays' 	=> "Available Overlays",
	'membermap_mapmanager_preview' 			=> "A preview of (almost) all maps and overlays can be seen here",

	/* Permissions */
	'perm_membermap_perm__label'		=> '',
	'perm_membermap_perm__view'			=> 'See Group',
	'perm_membermap_perm__read'			=> "View Markers",
	'perm_membermap_perm__add'			=> "Add Markers",
	'perm_membermap_perm__reply'		=> "Comment",
	'perm_membermap_perm__review'		=> "Review",


	/* Front-end showmap */
	'membermap_adminTools' 				=> "Admin Tools",
	'membermap_button_addLocation' 		=> "Add Location",
	'membermap_button_editLocation' 	=> "Update Location",
	'membermap_current_location' 		=> "Use Current Location",
	'membermap_geolocation_desc' 		=> "This will use a feature in your browser to detect your current location using GPS, Cellphone triangulation, Wifi, Router, or IP address",
	'membermap_add_marker' 				=> "Add Custom Marker",
	'membermap_edit_marker' 			=> "Edit Custom Marker",
	'membermap_form_location' 			=> "Search for your location",
	'membermap_form_placeholder' 		=> "Enter your address / city / county / country, you can be as specific as you like",
	'membermap_button_myLocation' 		=> "My Location",
	'membermap_showing_markers'			=> "Showing <span>0</span> markers",
	'membermap_view_fullsize' 			=> "View fullsize map",
	'membermap_goHome' 					=> "Go to my location",
	'membermap_browse_markers'			=> "Browse Markers",
	'membermap_marker_group_Clubs'		=> "Club Locations",


	/* Front-end errors */
	'membermap_error_cantEdit' 	=> "You are not allowed to edit your location.",
	'membermap_error_cantAdd' 	=> "You are not allowed to add a location.",
	'membermap_error_noGroups' 	=> "You need to create a Custom Marker Group first.",
	'membermap_only_one_marker' => "You can only have one member marker. <a href='%s'>Edit your existing one.</a>",
	'membermap_noAPI_admin'		=> "A personal <a href='https://developer.mapquest.com/' target='_blank'>MapQuest API key</a> is required. Go to ACP > Community > Member Map > Settings to add yours. (This message is only visible to administrators)",
	'membermap_no_club' 		=> "Couldn't find what you were looking for. Showing all members.",

	/* Front-end marker form */
	'marker_title' 				=> "Marker Title",
	'marker_description' 		=> "Marker Description",
	'marker_lat' 				=> "Latitude (N)",
	'marker_location' 			=> "Location",
	'marker_location_desc' 		=> "Enter a location above to search for one, enter the latitude and longitude manually below, or select the location in the map",
	'marker_lon' 				=> "Longitude (E)",
	'marker_parent_id' 			=> "Marker Group",
	'marker_submit'				=> "Save Marker",

	/* Front-end admin tools */
	'membermap_rebuildBrowserCache' 		=> "Rebuild Browser Cache",
	'membermap_rebuildServerCache' 			=> "Rebuild Server Cache (Last Update: %s)",
	'membermap_rebuildServerCache_notSet' 	=> "Rebuild Server Cache (Not created yet)",

	/* Member List block */
	'block_memberList_staff'				=> "Staff members",
	'block_memberList_followers'			=> "Members you follow",
	'block_memberList_others'				=> "Other members",
	'block_memberList_members'				=> "Members",

	/* Digests */
	'x_created_marker_in'		=> "%s created a marker in %s",
	'x_commented_marker'		=> "%s commented on a marker",
);