<ips:template parameters="$orientation='vertical'" />
<div id="membermap_memberList">
	<div id="memberList_staff" class='ipsHide'>
		<h3 class='ipsType_reset ipsWidget_title'>
			{lang="block_memberList_staff"}
		</h3>
		<div class='ipsWidget_inner ipsPad'>
			<ul class='ipsList_noSpacing'>

			</ul>
		</div>
	</div>

	<div id="memberList_followers" class="ipsHide ipsSpacer_top">
		<h3 class='ipsType_reset ipsWidget_title'>
			{lang="block_memberList_followers"}
		</h3>
		<div class='ipsWidget_inner ipsPad'>
			<ul class='ipsList_noSpacing'>

			</ul>
		</div>
	</div>

	<div id="memberList_others" class="ipsHide ipsSpacer_top">
		<h3 class='ipsType_reset ipsWidget_title ipsHide'>
			{lang="block_memberList_others"}
		</h3>
		<div class='ipsWidget_inner ipsPad'>
			<ul class='ipsList_noSpacing'>

			</ul>
		</div>
	</div>
</div>