<ips:template parameters="" />
<div data-controller="membermap.admin.membermap.mapmanager">
	<div class='cMenuManager'>
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_veryWide cMenuManager_column'>
				<div class='cMenuManager_editorWrapper'>
					<div class='cMenuManager_main' data-manager='main'>
						<h2 class='acpBlock_title acpBlock_titleSmall acpBlock_titleDark ipsSpacer_top ipsSpacer_half'>
							{lang="membermap_mapmanager_activeMaps"}
						</h2>

						<div class='cMenuManager_root'>
							<ol class='cMenuManager_branch mapManager_baseMaps' id="mapManager_activeMaps">
							</ol>
						</div>
					</div>
				</div>
			</div>
			<div class='ipsColumn ipsColumn_veryWide cMenuManager_column'>
				<div class='cMenuManager_editorWrapper'>
					<div class='cMenuManager_main' data-manager='main'>
						<h2 class='acpBlock_title acpBlock_titleSmall acpBlock_titleDark ipsSpacer_top ipsSpacer_half'>
							{lang="membermap_mapmanager_availMaps"}
						</h2>

						<div class='cMenuManager_root'>
							<ol class='cMenuManager_branch mapManager_baseMaps' id="mapManager_availMaps">
							</ol>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class='ipsClearfix'></div>


		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_veryWide cMenuManager_column'>
				<div class='cMenuManager_editorWrapper'>
					<div class='cMenuManager_main' data-manager='main'>
						<h2 class='acpBlock_title acpBlock_titleSmall acpBlock_titleDark ipsSpacer_top ipsSpacer_half'>
							{lang="membermap_mapmanager_activeOverlays"}
						</h2>

						<div class='cMenuManager_root'>
							<ol class='cMenuManager_branch mapManager_overlays' id="mapManager_activeOverlays">
							</ol>
						</div>
					</div>
				</div>
			</div>
			<div class='ipsColumn ipsColumn_veryWide cMenuManager_column'>
				<div class='cMenuManager_editorWrapper'>
					<div class='cMenuManager_main' data-manager='main'>
						<h2 class='acpBlock_title acpBlock_titleSmall acpBlock_titleDark ipsSpacer_top ipsSpacer_half'>
							{lang="membermap_mapmanager_availOverlays"}
						</h2>

						<div class='cMenuManager_root'>
							<ol class='cMenuManager_branch mapManager_overlays' id="mapManager_availOverlays">
							</ol>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>